[build]
  # This is the directory to change to before starting a build.
  base    = "7-cli-sfc/solution/"
  # NOTE: This is where we will look for package.json/.nvmrc/etc, not root.
  # This is the directory that you are publishing from (relative to root of your repo)
  publish = "/"
  # This will be your default build command
  command = "npm run build"

[context.production]
  [context.production.environment]
    FROM_NETLIFY = "true"

[[redirects]]
  from = "/7-cli-sfc/solution/dist/*"
  to = "/7-cli-sfc/solution/dist/index.html"
  status = 200

[[headers]]
  for = "/**/*.woff"
  [headers.values]
    Access-Control-Allow-Origin = "*"

  for = "/**/*.ttf"
  [headers.values]
    Access-Control-Allow-Origin = "*"
